version: "3"

services:
    revproxy:
        image: nginx
        restart: always
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
          - "80:80"
        networks:
          - frontend
        depends_on:
          - web

    backendprocess:
        build:
            dockerfile: Dockerfile-node
            context: ./dockerfiles/
        restart: always
        env_file: "env"
        networks:
          - frontend
          - backend
        working_dir: /home/node/app
        volumes:
          - ./node:/home/node/app
        command: bash -c "npm start"
        depends_on:
          - db

    web:
        build:
            dockerfile: Dockerfile-php
            context: ./dockerfiles/
        networks:
          - frontend
          - backend
        volumes:
          - ./code:/var/www/html
        depends_on:
          - db
        restart: always
    db:
        image: mariadb
        restart: always
        env_file: "env"
        networks:
          - backend
        ports:
          - 3306:3306
        volumes:
          - ./db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        env_file: "env"
        ports:
          - "8080:80"
        networks:
            - backend
        depends_on:
          - db
        restart: always


networks:
  frontend:
  backend:
  